### ISSUE TITLE
Create a free and OBS friendly version of this

### ISSUE THREAD

**Issue by tamara-schmitz** [tamara-schmitz/ffmpeg-docker-container#2]
Let's make a version of this that does not include packman and can be built on https://build.opensuse.org

**Comment by tamara-schmitz** [comment]
Implemented in 93081beb5554fe8455714d481b24faf07b988464 and 2eb80317d7177c40bf7692ba44931ceab0304b0d. The patent free version is available on the GitHub registry under: ghcr.io/tamara-schmitz/ffmpeg-docker-container-free

**Comment by Martchus** [comment]
Thanks!

**Comment by tamara-schmitz** [comment]
And it's on OBS now as `registry.opensuse.org/home/tschmitz/branches/opensuse/templates/images/tumbleweed/containers/opensuse/ffmpeg`
